using System.Collections.Generic;
using Godot;

namespace INISOnline.Audio;

/// <summary>
/// Autoloaded audio service: loads user settings, plays pooled SFX on the SFX/UI buses, and a
/// looping music track on the Music bus. A single <see cref="Instance"/> is reachable from any
/// screen (e.g. button clicks). Royalty-free audio is generated by <c>tools/gen-audio.py</c>.
/// </summary>
public partial class AudioManager : Node
{
    public static AudioManager? Instance { get; private set; }

    private readonly Dictionary<string, AudioStream> _sfx = new();
    private readonly List<AudioStreamPlayer> _sfxPool = new();
    private int _sfxCursor;
    private AudioStreamPlayer _uiPlayer = null!;
    private AudioStreamPlayer _musicPlayer = null!;
    private bool _loopMusic;

    public override void _Ready()
    {
        Instance = this;
        Settings.Load();

        foreach (var name in new[] { "click", "draw", "place", "chime", "error", "victory" })
        {
            var stream = GD.Load<AudioStream>($"res://audio/sfx/{name}.wav");
            if (stream is not null) _sfx[name] = stream;
        }

        for (var i = 0; i < 6; i++)
        {
            var p = new AudioStreamPlayer { Bus = "SFX" };
            AddChild(p);
            _sfxPool.Add(p);
        }
        _uiPlayer = new AudioStreamPlayer { Bus = "UI" };
        AddChild(_uiPlayer);
        _musicPlayer = new AudioStreamPlayer { Bus = "Music" };
        _musicPlayer.Finished += () => { if (_loopMusic) _musicPlayer.Play(); };
        AddChild(_musicPlayer);
    }

    public void PlayUi()
    {
        if (_sfx.TryGetValue("click", out var s)) { _uiPlayer.Stream = s; _uiPlayer.Play(); }
    }

    public void PlaySfx(string name)
    {
        if (!_sfx.TryGetValue(name, out var stream)) return;
        var player = _sfxPool[_sfxCursor];
        _sfxCursor = (_sfxCursor + 1) % _sfxPool.Count;
        player.Stream = stream;
        player.Play();
    }

    public void PlayMusic(string track, bool loop = true)
    {
        var stream = GD.Load<AudioStream>($"res://audio/music/{track}.wav");
        if (stream is null) return;
        _loopMusic = loop;
        if (_musicPlayer.Stream == stream && _musicPlayer.Playing) return;

        if (_musicPlayer.Playing)
        {
            // Crossfade: ease the old track out, then bring the new one in.
            var fade = CreateTween();
            fade.TweenProperty(_musicPlayer, "volume_db", -30f, 0.8f);
            fade.TweenCallback(Callable.From(() =>
            {
                _musicPlayer.Stream = stream;
                _musicPlayer.Play();
            }));
            fade.TweenProperty(_musicPlayer, "volume_db", 0f, 0.8f);
            return;
        }
        _musicPlayer.VolumeDb = 0f;
        _musicPlayer.Stream = stream;
        _musicPlayer.Play();
    }

    public void StopMusic()
    {
        _loopMusic = false;
        _musicPlayer.Stop();
    }
}
